# Generated by Django 3.2.9 on 2022-02-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
